### ISSUE TITLE
in mac It sends error

### ISSUE THREAD

**Issue by therpro** [TacticalSpoon331/Discord-token-loggers#6]
File "MacTokenLogger.py", line 13
    appdatapath = (f'/Users/{getpass.getuser()}/Library/Application Support')

**Comment by TacticalSpoon331** [comment]
Cap

**Comment by therpro** [comment]
yes cap now it is
<img width="581" alt="Screenshot 2022-08-31 at 19 55 09" src="https://user-images.githubusercontent.com/105553374/187747104-cda00259-5f28-49c3-8710-58f623b0d7a2.png">

**Comment by pwndr** [comment]
you must do pip install requests
